-- Create Users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL
);

-- Create Books table
CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(100) NOT NULL,
    availability NUMBER(1) DEFAULT 1 -- 1 means available, 0 means checked out
);

-- Insert Sample Data into books table
INSERT INTO books (title, author, availability) 
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1);

INSERT INTO books (title, author, availability) 
VALUES ('1984', 'George Orwell', 1);

INSERT INTO books (title, author, availability) 
VALUES ('To Kill a Mockingbird', 'Harper Lee', 0);

-- Insert Sample User into users table
INSERT INTO users (username, password) 
VALUES ('admin', 'admin123');

-- Commit the changes
COMMIT;
